services:
  backend:
    build: ./pathwaybr-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pathwaybr
volumes:
  db-data: